Werkstueck-Sortieranlage: Motor Class Reference
Motor Class Reference
#include <Motor.h>
Public Member Functions
virtual ~Motor ()
void rechtslauf (bool ein)
void linkslauf (bool ein)
void langsam (bool ein)
void stopp (bool ein)
Private Member Functions
Motor ()
Friends
class HAL
Detailed Description
Ueber den Motor wird das Fliessbands betrieben.
Hier werden Methoden zur Verfuegung gestellt, um das Fliessband nach rechts, nach links, langsam oder normal laufen zu lassen oder zu stoppen.
Definition at line 19 of file Motor.h.
Constructor & Destructor Documentation
Motor::~Motor () virtual
Definition at line 14 of file Motor.cpp.
Motor::Motor () private
Definition at line 10 of file Motor.cpp.
Member Function Documentation
void Motor::langsam (bool ein)
Schaltet den langsamen Betrieb des Fliessbands ein oder aus.
Parameters
ein Wahr, wenn das Fliessband langsam laufen soll. Falsch, wenn das Fliessband normal laufen soll.
Bit des langsamen Laufs auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 52 of file Motor.cpp.
References HAL::getInstance(), MOTOR_LANGSAM, PORT_A, and HAL::set().
Referenced by TestKomponenten::motor().
void Motor::linkslauf (bool ein)
Schaltet den Linkslauf des Fliessbands ein oder aus.
Parameters
ein Wahr, wenn der Linkslauf eingeschaltet werden soll. Falsch, wenn der Linkslauf ausgeschlatet werden soll.
Bit des Linkslaufs auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 39 of file Motor.cpp.
References HAL::getInstance(), MOTOR_LINKSLAUF, PORT_A, and HAL::set().
Referenced by TestKomponenten::motor().
void Motor::rechtslauf (bool ein)
Schaltet den Rechtslauf des Fliessbands ein oder aus.
Parameters
ein Wahr, wenn der Rechtslauf eingeschaltet werden soll. Falsch, wenn der Rechtslauf ausgeschlatet werden soll.
Bit des Rechtslaufs auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 26 of file Motor.cpp.
References HAL::getInstance(), MOTOR_RECHTSLAUF, PORT_A, and HAL::set().
Referenced by TestKomponenten::motor().
void Motor::stopp (bool ein)
Schaltet den Betrieb des Fliessbands ein oder aus.
Parameters
ein Wahr, wenn das Fliessband stoppen soll. Falsch, wenn das Fliessband betrieben werden soll.
Bit zum Stoppen des Fliessbands auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 65 of file Motor.cpp.
References HAL::getInstance(), MOTOR_STOPP, PORT_A, and HAL::set().
Referenced by TestKomponenten::motor().
Friends And Related Function Documentation
friend class HAL friend
Definition at line 29 of file Motor.h.
The documentation for this class was generated from the following files:
Motor.h
Motor.cpp