Werkstueck-Sortieranlage: SerielleSchnittstelle Class Reference
SerielleSchnittstelle Class Reference
#include <SerielleSchnittstelle.h>
Public Member Functions
void sendeWerkstueck (const Werkstueck *werkstueck)
void empfangeWerkstueck (Werkstueck *werkstueck)
Static Public Member Functions
static SerielleSchnittstelle & getInstance ()
Private Member Functions
SerielleSchnittstelle ()
virtual ~SerielleSchnittstelle ()
void sendeDaten (const void *buf, ssize_t nbyte)
void empfangeDaten (void *buf, ssize_t nbyte)
Private Attributes
pthread_mutex_t mutex
Detailed Description
Ueber die SerielleSchnittstelle kommunizieren die beiden Fliessbandanlagen miteinander.
Diese Klasse ist als Singleton implementiert. Daher ist das einzige Objekt nur durch getInstance() erreichbar. Hier werden Methoden zur Verfuegung gestellt, um Daten ueber die SerielleSchnittstelle zu senden oder zu empfangen.
Definition at line 24 of file SerielleSchnittstelle.h.
Constructor & Destructor Documentation
SerielleSchnittstelle::SerielleSchnittstelle () private
SerielleSchnittstelle Konstruktor
Mutex wird initialisiert.
Definition at line 19 of file SerielleSchnittstelle.cpp.
References mutex.
SerielleSchnittstelle::~SerielleSchnittstelle () private virtual
SerielleSchnittstelle Destruktor
Mutex wird zerstoert.
Definition at line 30 of file SerielleSchnittstelle.cpp.
References mutex.
Member Function Documentation
void SerielleSchnittstelle::empfangeDaten (void * buf, ssize_t nbyte) private
Empfaengt Daten.
Parameters
buf Buffer fuer die Daten, welche empfangen werden.
nbyte Groesse des Buffer, fuer die Daten.
Mutex wird gesperrt. SerielleSchnittstelle wird geoeffnet. Daten werden empfangen. SerielleSchnittstelle wird geschlossen. Mutex wird entsperrt.
Definition at line 120 of file SerielleSchnittstelle.cpp.
References DEVICE, and mutex.
Referenced by empfangeWerkstueck().
void SerielleSchnittstelle::empfangeWerkstueck (Werkstueck * werkstueck)
Empfaengt die Daten zu einem Werkstueck.
Parameters
werkstueck Werkstueck Struktur, in welchem das empfangene Werkstueck abgelegt werden soll.
Empfaengt das Werkstueck mittels empfangeDaten().
Definition at line 71 of file SerielleSchnittstelle.cpp.
References empfangeDaten().
Referenced by TestSerielleSchnittstelle::empfangen().
SerielleSchnittstelle & SerielleSchnittstelle::getInstance () static
Liefert Objekt des Singleton.
Returns
Einziges Objekt von SerielleSchnittstelle
Singleton nach Meyers Singleton implementiert.
Definition at line 43 of file SerielleSchnittstelle.cpp.
Referenced by TestSerielleSchnittstelle::empfangen(), and TestSerielleSchnittstelle::senden().
void SerielleSchnittstelle::sendeDaten (const void * buf, ssize_t nbyte) private
Sendet Daten.
Parameters
buf Buffer fuer die Daten, welche gesendet werden sollen.
nbyte Groesse des Buffer, fuer die Daten.
Mutex wird gesperrt. SerielleSchnittstelle wird geoeffnet. Daten werden gesendet. 200 Millisekunden lang wird gewartet. SerielleSchnittstelle wird geschlossen. Mutex wird entsperrt.
Definition at line 90 of file SerielleSchnittstelle.cpp.
References DEVICE, and mutex.
Referenced by sendeWerkstueck().
void SerielleSchnittstelle::sendeWerkstueck (const Werkstueck * werkstueck)
Sendet die Daten zu einem Werkstueck.
Parameters
werkstueck Werkstueck Struktur, welche gesendet werden soll.
Sendet das Werkstueck mittels sendeDaten().
Definition at line 58 of file SerielleSchnittstelle.cpp.
References sendeDaten().
Referenced by TestSerielleSchnittstelle::senden().
Member Data Documentation
pthread_mutex_t SerielleSchnittstelle::mutex private
Definition at line 35 of file SerielleSchnittstelle.h.
Referenced by empfangeDaten(), sendeDaten(), SerielleSchnittstelle(), and ~SerielleSchnittstelle().
The documentation for this class was generated from the following files:
SerielleSchnittstelle.h
SerielleSchnittstelle.cpp