Werkstueck-Sortieranlage: Bedienpanel Class Reference
Bedienpanel Class Reference
#include <Bedienpanel.h>
Public Member Functions
virtual ~Bedienpanel ()
void led_Starttaste (bool ein)
void led_Resettaste (bool ein)
void led_Q1 (bool ein)
void led_Q2 (bool ein)
Private Member Functions
Bedienpanel ()
Friends
class HAL
Detailed Description
Ansteuerung des Bedienpanel.
Hier werden Methoden zur Verfuegung gestellt, um die LED auf dem Bedienpanel leuchten zu lassen.
Definition at line 19 of file Bedienpanel.h.
Constructor & Destructor Documentation
Bedienpanel::~Bedienpanel () virtual
Definition at line 14 of file Bedienpanel.cpp.
Bedienpanel::Bedienpanel () private
Definition at line 10 of file Bedienpanel.cpp.
Member Function Documentation
void Bedienpanel::led_Q1 (bool ein)
Schaltet die LED Q1 ein oder aus.
Parameters
ein Wahr, wenn die LED eingeschaltet werden soll. Falsch, wenn die LED ausgeschlatet werden soll.
Bit der LED Q1 auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 52 of file Bedienpanel.cpp.
References HAL::getInstance(), LED_Q1, PORT_C, and HAL::set().
Referenced by TestKomponenten::bedienpanel().
void Bedienpanel::led_Q2 (bool ein)
Schaltet die LED Q2 ein oder aus.
Parameters
ein Wahr, wenn die LED eingeschaltet werden soll. Falsch, wenn die LED ausgeschlatet werden soll.
Bit der LED Q2 auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 65 of file Bedienpanel.cpp.
References HAL::getInstance(), LED_Q2, PORT_C, and HAL::set().
Referenced by TestKomponenten::bedienpanel().
void Bedienpanel::led_Resettaste (bool ein)
Schaltet die Resettasten-LED ein oder aus.
Parameters
ein Wahr, wenn die LED eingeschaltet werden soll. Falsch, wenn die LED ausgeschlatet werden soll.
Bit der Resettasten-LED auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 39 of file Bedienpanel.cpp.
References HAL::getInstance(), LED_RESETTASTE, PORT_C, and HAL::set().
Referenced by TestKomponenten::bedienpanel().
void Bedienpanel::led_Starttaste (bool ein)
Schaltet die Starttasten-LED ein oder aus.
Parameters
ein Wahr, wenn die LED eingeschaltet werden soll. Falsch, wenn die LED ausgeschlatet werden soll.
Bit der Starttasten-LED auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 26 of file Bedienpanel.cpp.
References HAL::getInstance(), LED_STARTTASTE, PORT_C, and HAL::set().
Referenced by TestKomponenten::bedienpanel().
Friends And Related Function Documentation
friend class HAL friend
Definition at line 33 of file Bedienpanel.h.
The documentation for this class was generated from the following files:
Bedienpanel.h
Bedienpanel.cpp