Werkstueck-Sortieranlage: TestSerielleSchnittstelle Class Reference
TestSerielleSchnittstelle Class Reference
#include <TestSerielleSchnittstelle.h>
Static Public Member Functions
static void starten (bool automatik, unsigned int wiederholungen)
Static Private Member Functions
static void senden ()
static void empfangen ()
Detailed Description
Klasse zum Testen der Kommunikation ueber die SerielleSchnittstelle.
Mit der statischen Methode starten() wird der Test der seriellen Schnittstelle gestartet.
Definition at line 19 of file TestSerielleSchnittstelle.h.
Member Function Documentation
void TestSerielleSchnittstelle::empfangen () static private
Testet das Empfangen von Daten ueber die SerielleSchnittstelle.
Ein Werkstueck wird mittels der SerielleSchnittstelle empfangen. Anschliessend werden die Daten des empfangenen Werkstuecks ausgegeben.
Definition at line 96 of file TestSerielleSchnittstelle.cpp.
References SerielleSchnittstelle::empfangeWerkstueck(), SerielleSchnittstelle::getInstance(), Werkstueck::hoehen, Werkstueck::id, and Werkstueck::typ.
void TestSerielleSchnittstelle::senden () static private
Testet das Senden von Daten ueber die SerielleSchnittstelle.
Ein Werkstueck wird erstellt, mit zufaelligen Daten gefuellt und mittels der SerielleSchnittstelle gesendet. Anschliessend werden die Daten des gesendeten Werkstuecks ausgegeben.
Definition at line 69 of file TestSerielleSchnittstelle.cpp.
References BOHRUNG_OBEN_METALL, SerielleSchnittstelle::getInstance(), Werkstueck::hoehen, Werkstueck::id, SerielleSchnittstelle::sendeWerkstueck(), and Werkstueck::typ.
void TestSerielleSchnittstelle::starten (bool automatik, unsigned int wiederholungen) static
Startet den Test der seriellen Schnittstelle.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
wiederholungen Die Anzahl der Wiederholungen des Tests.
Fuer jede Wiederholung des Tests werden einmal Daten gesendet und einmal Daten empfangen. Dies ist in die Methoden senden() und empfangen() unterteilt. Wenn der Test automatisch ausgefuehrt werden soll, wird der Test die bestimmte Anzahl Wiederholungen ausgefuehrt. Wenn der Test manuell ausgefuehrt werden soll, wird auf eine beliebige Eingabe gewartet und dann der Test wiederholt. In dem Fall bestimmt der Tester wie oft der Test wiederholt wird. Wenn der Tester den in dem Makro KOMMANDO_TEST_BEENDEN definierten String eingibt wird das Testen beendet.
Definition at line 33 of file TestSerielleSchnittstelle.cpp.
References KOMMANDO_TEST_BEENDEN.
Referenced by main().
The documentation for this class was generated from the following files:
TestSerielleSchnittstelle.h
TestSerielleSchnittstelle.cpp