Werkstueck-Sortieranlage: Blinker Class Reference
Blinker Class Reference
#include <Blinker.h>
Public Member Functions
virtual ~Blinker ()
virtual void execute (void *arg)
virtual void shutdown ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Private Member Functions
Blinker (useconds_t millisekunden, uint8_t lampe)
Private Attributes
useconds_t mikrosekunden
uint8_t val
Friends
class Ampel
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Ein Blinker wird von der Ampel gestartet, um eine bestimmte Lampe blinken zu lassen.
Diese Klasse erbt von der Klasse HAWThread und muss auch gestartet werden um zu funktionieren. Hier wird eine bestimmte Lampe immer wieder ein- und ausgeschaltet, bis der Thread gestoppt wird.
Definition at line 23 of file Blinker.h.
Constructor & Destructor Documentation
Blinker::~Blinker () virtual
Definition at line 29 of file Blinker.cpp.
Blinker::Blinker (useconds_t millisekunden, uint8_t lampe) private
Blinker Konstruktor
Parameters
millisekunden Die Anzahl der Millisekunden, in welcher die Lampe ein- oder ausgeschaltet sein soll.
lampe Das Bit der Lampe, welche ein- und ausgeschaltet werden soll.
Die Anzahl der Millisekunden wird in Mikrosekunden umgewandelt.
Definition at line 22 of file Blinker.cpp.
References mikrosekunden, and val.
Member Function Documentation
void Blinker::execute (void * arg) virtual
Von HAWThread geerbte Methode, welche beim Starten des Thread aufgerufen wird.
Parameters
arg Der Parameter, welcher beim Starten des Thread uebergeben wird.
Schleife des Thread wird gestartet und laeuft bis der Thread gestoppt wird. Bit der bestimmten Lampe auf dem entsprechenden Port wird gesetzt. Mikrosekunden werden gewartet. Bit der bestimmten Lampe auf dem entsprechenden Port wird geloescht. Mikrosekunden werden gewartet.
Implements thread::HAWThread.
Definition at line 45 of file Blinker.cpp.
References HAL::getInstance(), thread::HAWThread::isStopped(), mikrosekunden, PORT_A, HAL::set(), and val.
void Blinker::shutdown () virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 59 of file Blinker.cpp.
Friends And Related Function Documentation
friend class Ampel friend
Definition at line 33 of file Blinker.h.
Member Data Documentation
useconds_t Blinker::mikrosekunden private
Definition at line 31 of file Blinker.h.
Referenced by Blinker(), and execute().
uint8_t Blinker::val private
Definition at line 32 of file Blinker.h.
Referenced by Blinker(), and execute().
The documentation for this class was generated from the following files:
Blinker.h
Blinker.cpp