Werkstueck-Sortieranlage: HAL Class Reference
HAL Class Reference
#include <HAL.h>
Public Member Functions
void set (uintptr_t port, uint8_t val, bool on)
bool isSet (uintptr_t port, uint8_t val)
bool lichtschrankeEinlauf ()
bool lichtschrankeAuslauf ()
InterruptController * getInterruptController ()
Bedienpanel * getBedienpanel ()
Ampel * getAmpel ()
Motor * getMotor ()
Weiche * getWeiche ()
Hoehenmesser * getHoehenmesser ()
Metalldetektor * getMetalldetektor ()
Rutsche * getRutsche ()
Static Public Member Functions
static HAL & getInstance ()
static void initialize ()
Private Member Functions
HAL ()
virtual ~HAL ()
void toggle (uintptr_t port, uint8_t val)
void out (uintptr_t port, uint8_t val)
uint8_t in (uintptr_t port)
Private Attributes
pthread_barrier_t barrier
mutexmap mutexe
InterruptController * interruptController
Bedienpanel * bedienpanel
Ampel * ampel
Motor * motor
Weiche * weiche
Hoehenmesser * hoehenmesser
Metalldetektor * metalldetektor
Rutsche * rutsche
Friends
class InterruptController
Detailed Description
Hardware Abstraction Layer (HAL)
Diese Klasse ist als Singleton implementiert. Daher ist das einzige Objekt nur durch getInstance() erreichbar. Hier ist die gesamte Ansteuerung der Hardware konzentriert.
Definition at line 89 of file HAL.h.
Constructor & Destructor Documentation
HAL::HAL () private
HAL Konstruktor
Barrier und Mutexe werden initialisiert. Control Port wird initialisiert. Objekte werden erstellt. InterruptController wird gestartet.
Definition at line 20 of file HAL.cpp.
References Ampel::Ampel(), ampel, barrier, bedienpanel, CONTROL, CONTROL_INITIALIZER, hoehenmesser, interruptController, InterruptController, metalldetektor, motor, mutexe, PORT_A, PORT_B, PORT_C, rutsche, thread::HAWThread::start(), and weiche.
HAL::~HAL () private virtual
HAL Destruktor
InterruptController wird gestoppt. Objekte werden geloescht. Mutexe werden zerstoert.
Definition at line 50 of file HAL.cpp.
References ampel, bedienpanel, hoehenmesser, interruptController, thread::HAWThread::join(), metalldetektor, motor, mutexe, rutsche, InterruptController::stop(), and weiche.
Member Function Documentation
Ampel * HAL::getAmpel ()
Definition at line 206 of file HAL.cpp.
References ampel.
Referenced by TestKomponenten::ampel(), and TestKomponenten::blinken().
Bedienpanel * HAL::getBedienpanel ()
Definition at line 201 of file HAL.cpp.
References bedienpanel.
Referenced by TestKomponenten::bedienpanel().
Hoehenmesser * HAL::getHoehenmesser ()
Definition at line 221 of file HAL.cpp.
References hoehenmesser.
HAL & HAL::getInstance () static
Liefert Objekt des Singleton.
Returns
Einziges Objekt der HAL
Singleton nach Meyers Singleton implementiert.
Definition at line 78 of file HAL.cpp.
Referenced by TestKomponenten::ampel(), Weiche::auf(), TestKomponenten::bedienpanel(), TestKomponenten::blinken(), Blinker::execute(), Ampel::gelb(), Ampel::gruen(), TestInterruptController::initialize(), InterruptController::initialize(), initialize(), Motor::langsam(), Bedienpanel::led_Q1(), Bedienpanel::led_Q2(), Bedienpanel::led_Resettaste(), Bedienpanel::led_Starttaste(), Motor::linkslauf(), main(), TestKomponenten::motor(), Motor::rechtslauf(), Ampel::rot(), Motor::stopp(), and TestKomponenten::weiche().
InterruptController * HAL::getInterruptController ()
Definition at line 196 of file HAL.cpp.
References interruptController.
Referenced by TestInterruptController::initialize().
Metalldetektor * HAL::getMetalldetektor ()
Definition at line 226 of file HAL.cpp.
References metalldetektor.
Motor * HAL::getMotor ()
Definition at line 211 of file HAL.cpp.
References motor.
Referenced by TestKomponenten::motor().
Rutsche * HAL::getRutsche ()
Definition at line 231 of file HAL.cpp.
References rutsche.
Weiche * HAL::getWeiche ()
Definition at line 216 of file HAL.cpp.
References weiche.
Referenced by TestKomponenten::weiche().
uint8_t HAL::in (uintptr_t port) private
Liest Thread sicher den Wert eines bestimmten Port.
Parameters
port Bestimmter Port, dessen Wert gelesen werden soll.
Returns
Gelesener Wert der bestimmten Port.
Sperrt den, dem Port zugehoerigen, Mutex, liest den Wert des bestimmten Port und entsperrt den Mutex anschliessend wieder.
Definition at line 183 of file HAL.cpp.
References mutexe.
Referenced by isSet(), and toggle().
void HAL::initialize () static
Initialiert das Objekt der HAL.
Muss vor Benutzung der HAL ein Mal aufgerufen werden. Wartet auf die Threads, welche mit der Instanziierung der HAL gestartet wurden. Barrier wird zerstoert.
Definition at line 93 of file HAL.cpp.
References barrier, and getInstance().
Referenced by main().
bool HAL::isSet (uintptr_t port, uint8_t val)
Prueft ob ein Port einen bestimmten Wert besitzt.
Parameters
port Der Port, dessen Wert geprueft werden soll.
val Bestimmter Wert, auf welchen der Port geprueft werden soll.
Returns
Wahr, wenn der Port den bestimmten Wert besitzt. Falsch, wenn nicht.
Liest den Wert des Port und verknuepft ihn mittels UND-Operator mit dem bestimmten Wert.
Definition at line 127 of file HAL.cpp.
References in().
Referenced by lichtschrankeAuslauf(), lichtschrankeEinlauf(), and set().
bool HAL::lichtschrankeAuslauf ()
Definition at line 137 of file HAL.cpp.
References isSet(), LICHTSCHRANKE_AUSLAUF, and PORT_B.
bool HAL::lichtschrankeEinlauf ()
Definition at line 132 of file HAL.cpp.
References isSet(), LICHTSCHRANKE_EINLAUF, and PORT_B.
void HAL::out (uintptr_t port, uint8_t val) private
Schreibt Thread sicher einen Wert auf einen Port.
Parameters
port Der Port, dessen Wert ueberschrieben werden soll.
val Der Wert, welcher auf den Port geschrieben werden soll.
Sperrt den, dem Port zugehoerigen, Mutex, schreibt den Wert auf den Port und entsperrt den Mutex anschliessend wieder.
Definition at line 165 of file HAL.cpp.
References mutexe.
Referenced by InterruptController::initialize(), and toggle().
void HAL::set (uintptr_t port, uint8_t val, bool on)
Setzt den Wert eines Port.
Parameters
port Der Port, dessen Wert gesetzt werden soll.
val Bit des Port, welches gesetzt werden sollen.
on Bestimmter Wert, auf welchen das Bit gesetzt werden sollen.
Setzt den Wert eines Port, wenn der Port nicht bereits den bestimmten Wert besitzt.
Definition at line 109 of file HAL.cpp.
References isSet(), and toggle().
Referenced by Weiche::auf(), Blinker::execute(), Ampel::gelb(), Ampel::gruen(), Motor::langsam(), Bedienpanel::led_Q1(), Bedienpanel::led_Q2(), Bedienpanel::led_Resettaste(), Bedienpanel::led_Starttaste(), Motor::linkslauf(), Motor::rechtslauf(), Ampel::rot(), and Motor::stopp().
void HAL::toggle (uintptr_t port, uint8_t val) private
Schaltet bestimmte Bits eines Port um
Parameters
port Der Port, dessen Bits umgeschaltet werden sollen.
val Bestimmte Bits, welche umgeschaltet werden sollen.
Liest den Wert des Port, verkuenpft ihn mittels exklusiv ODER-Operator mit den bestimmten Bits und schreibt das Ergebnis auf den Port.
Definition at line 151 of file HAL.cpp.
References in(), and out().
Referenced by set().
Friends And Related Function Documentation
friend class InterruptController friend
Definition at line 122 of file HAL.h.
Referenced by HAL().
Member Data Documentation
Ampel* HAL::ampel private
Definition at line 116 of file HAL.h.
Referenced by getAmpel(), HAL(), and ~HAL().
pthread_barrier_t HAL::barrier private
Definition at line 112 of file HAL.h.
Referenced by HAL(), and initialize().
Bedienpanel* HAL::bedienpanel private
Definition at line 115 of file HAL.h.
Referenced by getBedienpanel(), HAL(), and ~HAL().
Hoehenmesser* HAL::hoehenmesser private
Definition at line 119 of file HAL.h.
Referenced by getHoehenmesser(), HAL(), and ~HAL().
InterruptController* HAL::interruptController private
Definition at line 114 of file HAL.h.
Referenced by getInterruptController(), HAL(), and ~HAL().
Metalldetektor* HAL::metalldetektor private
Definition at line 120 of file HAL.h.
Referenced by getMetalldetektor(), HAL(), and ~HAL().
Motor* HAL::motor private
Definition at line 117 of file HAL.h.
Referenced by getMotor(), HAL(), and ~HAL().
mutexmap HAL::mutexe private
Definition at line 113 of file HAL.h.
Referenced by HAL(), in(), out(), and ~HAL().
Rutsche* HAL::rutsche private
Definition at line 121 of file HAL.h.
Referenced by getRutsche(), HAL(), and ~HAL().
Weiche* HAL::weiche private
Definition at line 118 of file HAL.h.
Referenced by getWeiche(), HAL(), and ~HAL().
The documentation for this class was generated from the following files:
HAL.h
HAL.cpp