Werkstueck-Sortieranlage: thread::HAWThread Class Reference
thread::HAWThread Class Reference abstract
#include <HAWThread.h>
Public Member Functions
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Protected Member Functions
void run (void *arg)
virtual void execute (void *)=0
virtual void shutdown ()=0
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions
static void * entryPoint (void *)
Private Attributes
pthread_t tid_
volatile bool bRunning_
void * Arg_
bool LOCAL_EXIT
Static Private Attributes
static volatile bool GLOBAL_EXIT = false
Detailed Description
Definition at line 30 of file HAWThread.h.
Constructor & Destructor Documentation
thread::HAWThread::HAWThread ()
Constructor. Initializes members
Definition at line 23 of file HAWThread.cpp.
thread::HAWThread::~HAWThread () virtual
Destructor. Calls ThreadDestroy. This should shutdown the thread more carefully.
Warning
needs some work!
Definition at line 29 of file HAWThread.cpp.
References tid_.
Member Function Documentation
void* thread::HAWThread::Arg () const inline protected
used internally to pass the argument.
Definition at line 93 of file HAWThread.h.
References Arg_.
Referenced by entryPoint(), and start().
void thread::HAWThread::Arg (void * a) inline protected
used internally to set the arguement.
Definition at line 97 of file HAWThread.h.
References Arg_.
void thread::HAWThread::cont ()
This function continues (resumes) the thread. It makes a ThreadCtrl call.
Definition at line 52 of file HAWThread.cpp.
References tid_.
void * thread::HAWThread::entryPoint (void * pthis) static protected
Definition at line 64 of file HAWThread.cpp.
References Arg(), and run().
Referenced by start().
virtual void thread::HAWThread::execute (void *) protected pure virtual
to be implemented in the derived class. The application programmer has to write his own loop. He can check bool isStopped() to see if the thread should exit the loop.
Implemented in InterruptController, Blinker, and TestInterruptController.
Referenced by run().
void thread::HAWThread::hold ()
This function holds (suspends) the thread. It makes a ThreadCtrl call. It shall be used if the thread is not being used for a while but may be used later
Definition at line 48 of file HAWThread.cpp.
References tid_.
bool thread::HAWThread::isStopped () const inline protected
returns the stop-status of the thread. This function should be checked by the user function execute regularly.
Definition at line 103 of file HAWThread.h.
References GLOBAL_EXIT, and LOCAL_EXIT.
Referenced by Blinker::execute(), and InterruptController::execute().
void thread::HAWThread::join () const
Calls join on the thread.
Warning
must be called from the same context as start.
Definition at line 71 of file HAWThread.cpp.
References tid_.
Referenced by Ampel::blinkerStopp(), TestInterruptController::starten(), and HAL::~HAL().
void thread::HAWThread::run (void * arg) protected
This is called when the thread is started. It calls execute an shutdown which are the user functions.
Definition at line 58 of file HAWThread.cpp.
References execute(), and shutdown().
Referenced by entryPoint().
virtual void thread::HAWThread::shutdown () protected pure virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implemented in InterruptController, Blinker, and TestInterruptController.
Referenced by run().
void thread::HAWThread::shutdownAll () inline protected
sets the GLOBAL_EXIT flag to true.
Definition at line 105 of file HAWThread.h.
References GLOBAL_EXIT.
void thread::HAWThread::start (void * arg)
Starts the Thread.
Warning
start must be called always from the same context as stop().
If Thread is already running, start() is a NOP.
argument is stored locally as a member.
Definition at line 34 of file HAWThread.cpp.
References Arg(), bRunning_, entryPoint(), and tid_.
Referenced by Ampel::gelbBlinken(), Ampel::gruenBlinken(), HAL::HAL(), Ampel::rotBlinken(), and TestInterruptController::starten().
void thread::HAWThread::stop ()
Sets the internal flag LOCAL_EXIT to true.
Definition at line 43 of file HAWThread.cpp.
References LOCAL_EXIT.
Referenced by Ampel::blinkerStopp(), and TestInterruptController::starten().
Member Data Documentation
void* thread::HAWThread::Arg_ private
argument stored locally. To be passed to user function.
Definition at line 109 of file HAWThread.h.
Referenced by Arg().
volatile bool thread::HAWThread::bRunning_ private
flag to check if thread is running
Definition at line 108 of file HAWThread.h.
Referenced by start().
volatile bool thread::HAWThread::GLOBAL_EXIT = false static private
if true, then all threads will close, if function isStopped is checked.
Definition at line 110 of file HAWThread.h.
Referenced by isStopped(), and shutdownAll().
bool thread::HAWThread::LOCAL_EXIT private
stops the local thread, if isStopped is checked.
Definition at line 111 of file HAWThread.h.
Referenced by isStopped(), and stop().
pthread_t thread::HAWThread::tid_ private
thread id to be passed to pthread_create
Definition at line 107 of file HAWThread.h.
Referenced by cont(), hold(), join(), start(), and ~HAWThread().
The documentation for this class was generated from the following files:
HAWThread.h
HAWThread.cpp