Werkstueck-Sortieranlage: Ampel Class Reference
Ampel Class Reference
#include <Ampel.h>
Public Member Functions
virtual ~Ampel ()
void gruenBlinken (int millisekunden)
void gelbBlinken (int millisekunden)
void rotBlinken (int millisekunden)
void gruen (bool ein)
void gelb (bool ein)
void rot (bool ein)
Private Member Functions
Ampel ()
void blinkerStopp (Blinker *blinker)
Private Attributes
Blinker * gruenBlinker
Blinker * gelbBlinker
Blinker * rotBlinker
Friends
class HAL
Detailed Description
Ueber die Ampel werden die drei farbigen Lampen angesteuert.
Hier werden Methoden zur Verfuegung gestellt, um die Ampel gruen, gelb oder rot leuchten oder blinken zu lassen. Fuer das Blinken wird jeweils ein eigener Thread der Klasse Blinker beauftragt.
Definition at line 23 of file Ampel.h.
Constructor & Destructor Documentation
Ampel::~Ampel () virtual
Ampel Destruktor
Alle Blinker werden, mittels blinkerStopp(), gestoppt.
Definition at line 20 of file Ampel.cpp.
References blinkerStopp(), gelbBlinker, gruenBlinker, and rotBlinker.
Ampel::Ampel () private
Definition at line 10 of file Ampel.cpp.
Referenced by HAL::HAL().
Member Function Documentation
void Ampel::blinkerStopp (Blinker * blinker) private
Stoppt einen Blinker.
Parameters
blinker Der Blinker, welcher gestoppt werden soll.
Der Blinker wird nur gestoppt, wenn er vorher instanziiert wurde. Der Thread wird gestoppt. Das Objekt wird geloescht.
Definition at line 139 of file Ampel.cpp.
References thread::HAWThread::join(), and thread::HAWThread::stop().
Referenced by gelb(), gelbBlinken(), gruen(), gruenBlinken(), rot(), rotBlinken(), and ~Ampel().
void Ampel::gelb (bool ein)
Schaltet die gelbe Lampe ein oder aus.
Parameters
ein Wahr, wenn die Lampe eingeschaltet werden soll. Falsch, wenn die Lampe ausgeschlatet werden soll.
Entsprechender Blinker wird gegebenenfalls gestoppt und geloescht. Bit der gelben Lampe auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 106 of file Ampel.cpp.
References AMPEL_GELB, blinkerStopp(), gelbBlinker, HAL::getInstance(), PORT_A, and HAL::set().
Referenced by TestKomponenten::ampel(), and TestKomponenten::blinken().
void Ampel::gelbBlinken (int millisekunden)
Laesst die gelbe Lampe blinken.
Parameters
millisekunden Die Anzahl der Millisekunden, in welcher die Lampe ein- und ausgeschaltet sein soll.
Blinker wird gegebenenfalls gestoppt und geloescht. Neuer Blinker wird instanziiert und gestartet.
Definition at line 54 of file Ampel.cpp.
References AMPEL_GELB, blinkerStopp(), gelbBlinker, and thread::HAWThread::start().
Referenced by TestKomponenten::blinken().
void Ampel::gruen (bool ein)
Schaltet die gruene Lampe ein oder aus.
Parameters
ein Wahr, wenn die Lampe eingeschaltet werden soll. Falsch, wenn die Lampe ausgeschlatet werden soll.
Entsprechender Blinker wird gegebenenfalls gestoppt und geloescht. Bit der gruenen Lampe auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 90 of file Ampel.cpp.
References AMPEL_GRUEN, blinkerStopp(), HAL::getInstance(), gruenBlinker, PORT_A, and HAL::set().
Referenced by TestKomponenten::ampel(), and TestKomponenten::blinken().
void Ampel::gruenBlinken (int millisekunden)
Laesst die gruene Lampe blinken.
Parameters
millisekunden Die Anzahl der Millisekunden, in welcher die Lampe ein- oder ausgeschaltet sein soll.
Blinker wird gegebenenfalls gestoppt und geloescht. Neuer Blinker wird instanziiert und gestartet.
Definition at line 36 of file Ampel.cpp.
References AMPEL_GRUEN, blinkerStopp(), gruenBlinker, and thread::HAWThread::start().
Referenced by TestKomponenten::blinken().
void Ampel::rot (bool ein)
Schaltet die rote Lampe ein oder aus.
Parameters
ein Wahr, wenn die Lampe eingeschaltet werden soll. Falsch, wenn die Lampe ausgeschlatet werden soll.
Entsprechender Blinker wird gegebenenfalls gestoppt und geloescht. Bit der roten Lampe auf dem entsprechenden Port wird gesetzt oder geloescht.
Definition at line 122 of file Ampel.cpp.
References AMPEL_ROT, blinkerStopp(), HAL::getInstance(), PORT_A, rotBlinker, and HAL::set().
Referenced by TestKomponenten::ampel(), and TestKomponenten::blinken().
void Ampel::rotBlinken (int millisekunden)
Laesst die rote Lampe blinken.
Parameters
millisekunden Die Anzahl der Millisekunden, in welcher die Lampe ein- und ausgeschaltet sein soll.
Entsprechender Blinker wird gegebenenfalls gestoppt und geloescht. Neuer Blinker wird instanziiert und gestartet.
Definition at line 72 of file Ampel.cpp.
References AMPEL_ROT, blinkerStopp(), rotBlinker, and thread::HAWThread::start().
Referenced by TestKomponenten::blinken().
Friends And Related Function Documentation
friend class HAL friend
Definition at line 39 of file Ampel.h.
Member Data Documentation
Blinker* Ampel::gelbBlinker private
Definition at line 37 of file Ampel.h.
Referenced by gelb(), gelbBlinken(), and ~Ampel().
Blinker* Ampel::gruenBlinker private
Definition at line 36 of file Ampel.h.
Referenced by gruen(), gruenBlinken(), and ~Ampel().
Blinker* Ampel::rotBlinker private
Definition at line 38 of file Ampel.h.
Referenced by rot(), rotBlinken(), and ~Ampel().
The documentation for this class was generated from the following files:
Ampel.h
Ampel.cpp