Werkstueck-Sortieranlage: InterruptController Class Reference
InterruptController Class Reference
#include <InterruptController.h>
Public Member Functions
virtual ~InterruptController ()
virtual void execute (void *arg)
virtual void shutdown ()
void stop ()
int getSignalChannelID ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Private Member Functions
InterruptController ()
void initialize (pthread_barrier_t *barrier)
Private Attributes
struct sigevent event
int interruptID
int isrChannelID
int signalChannelID
int signalConnectionID
uint16_t sival
Friends
class HAL
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Der InterruptController ist fuer die Erkennung der Interrupts zustaendig.
Diese Klasse erbt von der Klasse HAWThread und muss auch gestartet werden um zu funktionieren. Hier werden die Interrupts von der Interrupt Service Routine empfangen, aufbereitet und an den Signal Channel weitergeleitet.
Definition at line 27 of file InterruptController.h.
Constructor & Destructor Documentation
InterruptController::~InterruptController () virtual
Definition at line 56 of file InterruptController.cpp.
InterruptController::InterruptController () private
Definition at line 52 of file InterruptController.cpp.
Member Function Documentation
void InterruptController::execute (void * arg) virtual
Von HAWThread geerbte Methode, welche beim Starten des Thread aufgerufen wird.
Parameters
arg Der Parameter, welcher beim Starten des Thread uebergeben wird. Enthaelt die Barrier, welche an die Methode initialize(), zur Synchronisation uebergeben wird.
Thread wird mit dem Aufruf von initialize() initialisiert. Schleife des Thread wird gestartet und laeuft bis der Thread gestoppt wird. In der Schleife werden die Pulse Messages der ISR empfangen, aufbereitet und mit einer weiteren Pulse Message an den Signal Channel gesendet. Der Code der neuen Pulse Message enthaelt die Information, ob der neue Wert des geaenderten Bit 1 oder 0 ist. Der Wert der neuen Pulse Message enthaelt das Bit, welches sich durch einen Interrupt geaendertet hat. Dabei ist der Wert als Port B konkatiniert mit Port C zu lesen.
Implements thread::HAWThread.
Definition at line 143 of file InterruptController.cpp.
References initialize(), isrChannelID, thread::HAWThread::isStopped(), signalConnectionID, and sival.
int InterruptController::getSignalChannelID ()
Stellt den Signal Channel zur Verfuegung.
Returns
Enthaelt die Signal Channel ID.
Liefert die Signal Channel ID, mit welcher sich andere Threads fuer den Empfang der Interrupt Informationen verbinden koennen.
Definition at line 233 of file InterruptController.cpp.
References signalChannelID.
Referenced by TestInterruptController::initialize().
void InterruptController::initialize (pthread_barrier_t * barrier) private
Initialisiert den InterruptController.
Parameters
barrier Die Barrier, an welcher sich die Methode meldet, wenn die Initialisierung abgeschlossen ist.
Channels und Connections fuer das Interrupt Message Passing werden erstellt. Aktiviert Interrupts und bindet die Interrupts an die ISR. Setzt den Interrupt Status Port zurueckt. Initialisiert die Interrupt Control Register. Initialisiert sival. Meldet sich anschliessend an der Barrier.
Definition at line 73 of file InterruptController.cpp.
References event, HAL::getInstance(), INTERRUPT_CONTROL, INTERRUPT_CONTROL_PORT_B, INTERRUPT_CONTROL_PORT_C, INTERRUPT_DISABLE, INTERRUPT_REQUEST, INTERRUPT_STATUS, interruptID, interruptServiceRoutine(), isrChannelID, isrConnectionID, HAL::out(), PORT_B, PORT_C, signalChannelID, signalConnectionID, and sival.
Referenced by execute().
void InterruptController::shutdown () virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 181 of file InterruptController.cpp.
void InterruptController::stop ()
Von HAWThread ueberschriebene Methode, welche zum Stoppen des Thread aufgerufen wird.
Die entsprechende Methode von HAWThread wird aufgerufen. Channels und Connections fuer das Interrupt Message Passing werden zerstoert. Deaktiviert Interrupts.
Definition at line 193 of file InterruptController.cpp.
References interruptID, isrChannelID, isrConnectionID, signalChannelID, and signalConnectionID.
Referenced by HAL::~HAL().
Friends And Related Function Documentation
friend class HAL friend
Definition at line 44 of file InterruptController.h.
Member Data Documentation
struct sigevent InterruptController::event private
Definition at line 38 of file InterruptController.h.
Referenced by initialize().
int InterruptController::interruptID private
Definition at line 39 of file InterruptController.h.
Referenced by initialize(), and stop().
int InterruptController::isrChannelID private
Definition at line 40 of file InterruptController.h.
Referenced by execute(), initialize(), and stop().
int InterruptController::signalChannelID private
Definition at line 41 of file InterruptController.h.
Referenced by getSignalChannelID(), initialize(), and stop().
int InterruptController::signalConnectionID private
Definition at line 42 of file InterruptController.h.
Referenced by execute(), initialize(), and stop().
uint16_t InterruptController::sival private
Definition at line 43 of file InterruptController.h.
Referenced by execute(), and initialize().
The documentation for this class was generated from the following files:
InterruptController.h
InterruptController.cpp