Werkstueck-Sortieranlage: TestKomponenten Class Reference
TestKomponenten Class Reference
#include <TestKomponenten.h>
Static Public Member Functions
static void starten (bool automatik, unsigned int sekunden)
Static Private Member Functions
static void ampel (bool automatik, unsigned int sekunden)
static void blinken (bool automatik, unsigned int sekunden)
static void motor (bool automatik, unsigned int sekunden)
static void weiche (bool automatik, unsigned int sekunden)
static void bedienpanel (bool automatik, unsigned int sekunden)
static void warten (bool automatik, unsigned int sekunden, unsigned int sekunden_maximum)
Detailed Description
Klasse zum Testen der Aktoren des HAL.
Mit der statischen Methode starten() wird der Komponententest gestartet.
Definition at line 19 of file TestKomponenten.h.
Member Function Documentation
void TestKomponenten::ampel (bool automatik, unsigned int sekunden) static private
Testet das Leuchten der Ampel.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, in welcher eine Komponente angesteuert werden soll.
Schaltet eine Lampe der Ampel ein, ruft die Methode warten() auf und schaltet die Lampe wieder aus. Dieser Vorgang wird fuer jede Lampe der Ampel wiederholt. Die Parameter werden an die Methode warten() weitergereicht.
Definition at line 52 of file TestKomponenten.cpp.
References Ampel::gelb(), HAL::getAmpel(), HAL::getInstance(), Ampel::gruen(), and Ampel::rot().
void TestKomponenten::bedienpanel (bool automatik, unsigned int sekunden) static private
Testet die LED des Bedienpanel.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, in welcher eine Komponente angesteuert werden soll.
Schaltet eine LED des Bedienpanel ein, ruft die Methode warten() auf und schaltet die LED wieder aus. Dieser Vorgang wird fuer jede LED des Bedienpanel wiederholt. Die Parameter werden an die Methode warten() weitergereicht.
Definition at line 184 of file TestKomponenten.cpp.
References HAL::getBedienpanel(), HAL::getInstance(), Bedienpanel::led_Q1(), Bedienpanel::led_Q2(), Bedienpanel::led_Resettaste(), and Bedienpanel::led_Starttaste().
void TestKomponenten::blinken (bool automatik, unsigned int sekunden) static private
Testet das Blinken der Ampel.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, in welcher eine Komponente angesteuert werden soll.
Schaltet die Blinken aller Lampen der Ampel ein, ruft die Methode warten() auf und schaltet alle Lampen wieder aus. Die Parameter werden an die Methode warten() weitergereicht.
Definition at line 87 of file TestKomponenten.cpp.
References Ampel::gelb(), Ampel::gelbBlinken(), HAL::getAmpel(), HAL::getInstance(), Ampel::gruen(), Ampel::gruenBlinken(), Ampel::rot(), and Ampel::rotBlinken().
void TestKomponenten::motor (bool automatik, unsigned int sekunden) static private
Testet den Motor des Fliessbands.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, in welcher eine Komponente angesteuert werden soll.
Schaltet eine Funktion des Motors ein, ruft die Methode warten() auf und schaltet auf naechste die Funktion um. Dieser Vorgang wird fuer jede Funktion des Motors wiederholt. Die Parameter werden an die Methode warten() weitergereicht.
Definition at line 113 of file TestKomponenten.cpp.
References HAL::getInstance(), HAL::getMotor(), Motor::langsam(), Motor::linkslauf(), Motor::rechtslauf(), and Motor::stopp().
void TestKomponenten::starten (bool automatik, unsigned int sekunden) static
Startet den Komponententest.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, in welcher eine Komponente angesteuert werden soll.
Die Tests sind in Gruppen unterteilt. Jede Gruppe wird in einer eigenen Methode getestet. Die Parameter werden an diese Methoden weitergereicht.
Definition at line 28 of file TestKomponenten.cpp.
Referenced by main().
void TestKomponenten::warten (bool automatik, unsigned int sekunden, unsigned int sekunden_maximum) static private
Wartet abhaengig davon, ob der Test automatisch oder manuell ausgefuehrt werden soll.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, welche gewartet werden soll.
sekunden_maximum Die Anzahl der Sekunden, welche maximal gewartet werden darf.
Wenn der Test automatisch ausgefuehrt werden soll, wird die bestimmte Anzahl an Sekunden gewartet. Es wird aber nicht laenger als die bestimmte maximale Anzahl an Sekunden gewartet, wenn diese ungleich 0 ist. Wenn der Test manuell ausgefuehrt werden soll, wird auf eine beliebige Eingabe gewartet. In dem Fall bestimmt der Tester wie lange die jeweilige Komponente getestet wird. Eine moeglicherweise angegebene, maximale Anzahl an Sekunden die gewartet werden darf, wird dabei nicht beruecksichtigt.
Definition at line 230 of file TestKomponenten.cpp.
void TestKomponenten::weiche (bool automatik, unsigned int sekunden) static private
Testet das Oeffnen und Schliessen der Weiche.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, in welcher eine Komponente angesteuert werden soll.
Oeffnet die Weiche, ruft die Methode warten() auf und schliesst die Weiche wieder. Die Parameter werden an die Methode warten() weitergereicht.
Definition at line 162 of file TestKomponenten.cpp.
References Weiche::auf(), HAL::getInstance(), HAL::getWeiche(), and WEICHE_AUF_SEKUNDEN_MAXIMUM.
The documentation for this class was generated from the following files:
TestKomponenten.h
TestKomponenten.cpp