Werkstueck-Sortieranlage: TestInterruptController Class Reference
TestInterruptController Class Reference
#include <TestInterruptController.h>
Public Member Functions
virtual void execute (void *arg)
virtual void shutdown ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Static Public Member Functions
static void starten (bool automatik, unsigned int sekunden)
Private Member Functions
void ausgeben (bool code, int val)
void initialize ()
Private Attributes
int signalChannelID
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Klasse zum Testen des InterruptController.
Mit der statischen Methode starten() wird der Test der Sensoren des HAL gestartet.
Definition at line 21 of file TestInterruptController.h.
Member Function Documentation
void TestInterruptController::ausgeben (bool code, int val) private
Gibt eine Pulse Message des InterruptController aus.
Parameters
code Der Code der Pulse Message.
val Der Wert der Pulse Message.
Wandelt den Code und den Wert der Pulse Message in lesbare Strings um und gibt sie aus.
Definition at line 68 of file TestInterruptController.cpp.
References HOEHENMESSUNG_CHECK, LICHTSCHRANKE_AUSLAUF, LICHTSCHRANKE_EINLAUF, LICHTSCHRANKE_HOEHENMESSUNG, LICHTSCHRANKE_WEICHE, METALLDETEKTOR_CHECK, RUTSCHE_VOLL, TASTE_ESTOPP, TASTE_RESET, TASTE_START, TASTE_STOPP, and WEICHE_OFFEN.
void TestInterruptController::execute (void * arg) virtual
Von HAWThread geerbte Methode, welche beim Starten des Thread aufgerufen wird.
Parameters
arg Der Parameter, welcher beim Starten des Thread uebergeben wird.
Thread wird mit dem Aufruf von initialize() initialisiert. Schleife des Thread wird gestartet und laeuft bis der Thread gestoppt wird. In der Schleife werden die Pulse Messages des InterruptController empfangen und als Parameter an die Methode ausgeben() uebergeben.
Implements thread::HAWThread.
Definition at line 145 of file TestInterruptController.cpp.
void TestInterruptController::initialize () private
Initialisiert den TestInterruptController.
Die Signal Channel ID wird vom InterruptController gelesen.
Definition at line 130 of file TestInterruptController.cpp.
References HAL::getInstance(), HAL::getInterruptController(), and InterruptController::getSignalChannelID().
void TestInterruptController::shutdown () virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 171 of file TestInterruptController.cpp.
void TestInterruptController::starten (bool automatik, unsigned int sekunden) static
Startet den Test der Sensoren des HAL.
Parameters
automatik Wahr, wenn der Test automatisch ausgefuehrt soll. Falsch, wenn der Test manuell ausgefuehrt werden soll.
sekunden Die Anzahl der Sekunden, welche gewartet werden soll.
Es wird ein Objekt des TestInterruptController erstellt und dessen Thread gestartet. Dieser Thread reagiert in der Methode execute() auf Pulse Messages des InterruptController. Nach dem Starten des Thread wird gewartet und anschliessend der Thread gestoppt. Wenn der Test automatisch ausgefuehrt werden soll, wird die bestimmte Anzahl an Sekunden gewartet. Wenn der Test manuell ausgefuehrt werden soll, wird gewartet bis der Tester den in dem Makro KOMMANDO_TEST_BEENDEN definierten String eingibt.
Definition at line 30 of file TestInterruptController.cpp.
References thread::HAWThread::join(), KOMMANDO_TEST_BEENDEN, thread::HAWThread::start(), and thread::HAWThread::stop().
Referenced by main().
Member Data Documentation
int TestInterruptController::signalChannelID private
Definition at line 30 of file TestInterruptController.h.
The documentation for this class was generated from the following files:
TestInterruptController.h
TestInterruptController.cpp